set(__QT_DEPLOY_TARGET_zfsmgr_qt_FILE C:/Users/eladi/work/ZFSMgr/build-windows-alt/zfsmgr_qt.exe)
set(__QT_DEPLOY_TARGET_zfsmgr_qt_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_zfsmgr_qt_RUNTIME_DLLS C:/Qt/6.10.2/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Concurrent.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Network.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_zfsmgr_helpers_test_FILE C:/Users/eladi/work/ZFSMgr/build-windows-alt/zfsmgr_helpers_test.exe)
set(__QT_DEPLOY_TARGET_zfsmgr_helpers_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_zfsmgr_helpers_test_RUNTIME_DLLS C:/Qt/6.10.2/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Core.dll)
