set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(FREEBSD_TRIPLE "$ENV{FREEBSD_TRIPLE}")
if(FREEBSD_TRIPLE STREQUAL "")
  set(FREEBSD_TRIPLE "x86_64-unknown-freebsd13")
endif()

if(DEFINED ENV{FREEBSD_SYSROOT} AND NOT "$ENV{FREEBSD_SYSROOT}" STREQUAL "")
  set(CMAKE_SYSROOT "$ENV{FREEBSD_SYSROOT}")
endif()

set(CMAKE_C_COMPILER   "$ENV{FREEBSD_CC}")
set(CMAKE_CXX_COMPILER "$ENV{FREEBSD_CXX}")

if(CMAKE_C_COMPILER STREQUAL "")
  set(CMAKE_C_COMPILER "clang")
endif()
if(CMAKE_CXX_COMPILER STREQUAL "")
  set(CMAKE_CXX_COMPILER "clang++")
endif()

set(CMAKE_C_COMPILER_TARGET   "${FREEBSD_TRIPLE}")
set(CMAKE_CXX_COMPILER_TARGET "${FREEBSD_TRIPLE}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

if(DEFINED ENV{QT6_FREEBSD_PREFIX} AND NOT "$ENV{QT6_FREEBSD_PREFIX}" STREQUAL "")
  list(PREPEND CMAKE_PREFIX_PATH "$ENV{QT6_FREEBSD_PREFIX}")
endif()
