set(CMAKE_SYSTEM_NAME Darwin)

set(OSXCROSS_TARGET "$ENV{OSXCROSS_TARGET}")
if(OSXCROSS_TARGET STREQUAL "")
  set(OSXCROSS_TARGET "x86_64-apple-darwin23")
endif()

if(DEFINED ENV{OSX_SYSROOT} AND NOT "$ENV{OSX_SYSROOT}" STREQUAL "")
  set(CMAKE_OSX_SYSROOT "$ENV{OSX_SYSROOT}")
endif()

set(CMAKE_C_COMPILER   "$ENV{OSXCROSS_CC}")
set(CMAKE_CXX_COMPILER "$ENV{OSXCROSS_CXX}")

if(CMAKE_C_COMPILER STREQUAL "")
  set(CMAKE_C_COMPILER "${OSXCROSS_TARGET}-clang")
endif()
if(CMAKE_CXX_COMPILER STREQUAL "")
  set(CMAKE_CXX_COMPILER "${OSXCROSS_TARGET}-clang++")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

if(DEFINED ENV{QT6_MACOS_PREFIX} AND NOT "$ENV{QT6_MACOS_PREFIX}" STREQUAL "")
  list(PREPEND CMAKE_PREFIX_PATH "$ENV{QT6_MACOS_PREFIX}")
endif()
