set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CROSS_TRIPLE_WINDOWS "$ENV{CROSS_TRIPLE_WINDOWS}")
if(CROSS_TRIPLE_WINDOWS STREQUAL "")
  set(CROSS_TRIPLE_WINDOWS "x86_64-w64-mingw32")
endif()

set(CMAKE_C_COMPILER   "${CROSS_TRIPLE_WINDOWS}-gcc")
set(CMAKE_CXX_COMPILER "${CROSS_TRIPLE_WINDOWS}-g++")
set(CMAKE_RC_COMPILER  "${CROSS_TRIPLE_WINDOWS}-windres")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# Qt cross builds need host-side Qt tools (moc/uic/rcc) in addition to target packages.
# Keep target prefixes first in CMAKE_PREFIX_PATH so Qt libs resolve to MinGW.
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

if(DEFINED ENV{QT6_WINDOWS_PREFIX} AND NOT "$ENV{QT6_WINDOWS_PREFIX}" STREQUAL "")
  list(PREPEND CMAKE_PREFIX_PATH "$ENV{QT6_WINDOWS_PREFIX}")
endif()

if(DEFINED ENV{QT6_HOST_PREFIX} AND NOT "$ENV{QT6_HOST_PREFIX}" STREQUAL "")
  list(APPEND CMAKE_PREFIX_PATH "$ENV{QT6_HOST_PREFIX}")
endif()
